apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-deployment
 labels:
   app: nodejs
spec:
 replicas: 1
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 3
 selector:
   matchLabels:
     app: nodejs
 template:
   metadata:
     labels:
       app: nodejs
   spec:
     containers:
     - name: nodejs
       image: 122877051904.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest
       ports:
       - containerPort: 80
       resources: 
         limits:
           cpu: 250m
           memory: 128Mi
         requests:
           cpu: 250m
           memory: 128Mi
     priorityClassName: high-priority